name: Ti

on:
  schedule:
    - cron: "*/11 * * * *"
  workflow_dispatch:
    branches:

jobs:
  build:
    env:
      PY_COLORS: "1"

    strategy:
      fail-fast: false
      max-parallel: 1
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.13"]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Brave Browser
      run: |
        echo "Installing Brave Browser..."
        sudo apt-get update -y
        sudo apt-get install -y apt-transport-https curl
        curl -fsSL https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg \
          | sudo gpg --yes --dearmor -o /usr/share/keyrings/brave-browser-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] \
          https://brave-browser-apt-release.s3.brave.com/ stable main" \
          | sudo tee /etc/apt/sources.list.d/brave-browser-release.list
        sudo apt-get update -y
        sudo apt-get install -y brave-browser
        brave-browser --version

    - name: Install WARP
      run: |
        echo "Setting up Cloudflare WARP..."
        sudo apt-get -y update
        curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg \
          | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
        echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] \
          https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" \
          | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
        sudo apt-get update && sudo apt-get install -y --no-install-recommends cloudflare-warp
        sudo warp-cli --accept-tos registration new
        sudo warp-cli --accept-tos mode warp+doh
        sudo warp-cli --accept-tos connect
        sleep 5
      shell: bash

    - name: Ensure connection is WARP'ed
      run: |
        echo "Validating WARP connectivity..."
        curl -s https://www.cloudflare.com/cdn-cgi/trace | grep "warp=on"
      shell: bash

    - name: Set Locale
      run: |
        sudo apt-get install tzdata locales -y
        sudo locale-gen en_US.UTF-8
        sudo localectl set-locale LANG="en_US.UTF-8"
        export LANG="en_US.UTF-8"
        sudo update-locale
        locale -a
        locale
        locale -c -k LC_NUMERIC
        localectl status

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade wheel
        pip install --upgrade seleniumbase pyautogui pymongo python-xlib

    - name: Install chromedriver
      run: |
        seleniumbase install chromedriver

    - name: Run python dodo.py --debug
      run: |
        python dodo.py --brave --incognito --do-not-track --xvfb --screenshot
