name: Test Proxies

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl unzip
      - name: Install V2Ray
        run: |
          curl -O https://raw.githubusercontent.com/v2fly/fhs-install-v2ray/master/install-release.sh
          sudo bash install-release.sh
          sudo apt purge curl unzip
          sudo systemctl enable v2ray
          sudo systemctl start v2ray
          sudo apt-get install -y jq curl unzip
          
      - name: Run proxy tester
        run: |
          chmod +x ./auto1.sh
          sudo ./auto1.sh
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: v2ray-logs
          path: /tmp/v2ray.log
