name: Test Proxies

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl unzip
      - name: Install WARP
        run: |
          echo "Setting up Cloudflare WARP..."
          sudo apt-get -y update
          curl -fsSL https://pkg.cloudflareclient.com/pubkey.gpg | sudo gpg --yes --dearmor --output /usr/share/keyrings/cloudflare-warp-archive-keyring.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/cloudflare-warp-archive-keyring.gpg] https://pkg.cloudflareclient.com/ $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/cloudflare-client.list
          sudo apt-get update && sudo apt-get install -y --no-install-recommends cloudflare-warp
          sudo warp-cli --accept-tos registration new
          sudo warp-cli --accept-tos mode warp+doh
          sudo warp-cli --accept-tos connect
          sleep 5
        shell: bash
      - name: Install V2Ray
        run: |
          mkdir -p ~/v2ray
          cd ~/v2ray
          curl -L -o v2ray.zip https://github.com/v2fly/v2ray-core/releases/latest/download/v2ray-linux-64.zip
          unzip v2ray.zip
          chmod +x v2ray

      - name: Run proxy tester
        run: |
          chmod +x ./auto.sh
          ./auto.sh
      - name: Upload logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: v2ray-logs
          path: /tmp/v2ray.log
